services:
  # InfluxDB - Time Series Database
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
    restart: unless-stopped
    networks:
      - iot-network

  # Mosquitto MQTT Broker
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    hostname: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped
    networks:
      - iot-network

  # Grafana - Visualization Platform
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    restart: unless-stopped
    depends_on:
      - influxdb
    networks:
      - iot-network

  # Node-RED - Flow-based programming for IoT
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    hostname: nodered
    ports:
      - "1880:1880"
    volumes:
      - nodered-data:/data
    restart: unless-stopped
    depends_on:
      - influxdb
      - mqtt
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  influxdb-data:
  influxdb-config:
  mosquitto-data:
  mosquitto-log:
  grafana-data:
  nodered-data: